# Wasmer deployment configuration for IB Physics Question Generator
# This file tells Wasmer to deploy this as a Node.js application

[package]
name = "ibphysiq"
version = "1.0.0"
description = "An AI-powered web application for generating IB Physics practice questions"

[build]
command = "npm run build:wasmer"
publish = [".next/standalone"]

[[module]]
name = "ibphysiq"
source = "node server.js"
interpreter = "nodejs"

[fs]
"node_modules" = "node_modules"
"public" = "public"
".next/static" = ".next/static"
".next/standalone" = ".next/standalone"

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "3000"

[serve]
command = "node server.js"